# Generated by Django 4.1 on 2022-11-02 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crewdashboard', '0002_remove_locations_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
