# Generated by Django 4.1 on 2022-11-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crewdashboard', '0003_alter_locations_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
