# Generated by Django 4.1 on 2022-10-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_comment_edited_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('change_self_comment', 'Can edit comments made by the user'), ('change_other_comment', 'Can edit comments made by other users'), ('delete_self_comment', 'Can delete comments made by the user'), ('delete_other_comment', 'Can delete comments made by other users')]},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('change_self_post', 'Can edit posts made by the user'), ('change_other_post', 'Can edit posts made by other users'), ('delete_self_post', 'Can delete posts made by the user'), ('delete_other_post', 'Can delete posts made by other users')]},
        ),
    ]
