# Generated by Django 4.1 on 2022-10-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('organik', 'ORGANIK'), ('anorganik', 'ANORGANIK'), ('B3', 'B3')], default='orgnaik', max_length=10)),
                ('alamat', models.TextField(max_length=100)),
                ('tanggal', models.DateField()),
                ('kontak', models.CharField(max_length=12)),
            ],
        ),
    ]
