# Generated by Django 4.1 on 2022-10-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksampah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='kodepos',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='kota',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='jenis',
            field=models.CharField(choices=[('organik', 'Organik'), ('anorganik', 'Anorganik'), ('B3', 'B3')], default='orgnaik', max_length=10),
        ),
    ]
