# Generated by Django 4.1 on 2022-10-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksampah', '0002_bank_kodepos_bank_kota_alter_bank_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='kodepos',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='kota',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
