# Generated by Django 4.1 on 2022-10-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banksampah', '0005_alter_bank_kodepos_alter_bank_kota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='kodepos',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='kota',
        ),
    ]
