# Generated by Django 4.1 on 2022-10-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksampah', '0006_remove_bank_kodepos_remove_bank_kota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='jenis',
            field=models.CharField(max_length=10),
        ),
    ]
