# Generated by Django 4.1 on 2022-10-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksampah', '0001_initial'),
    ]

    operations = [
    ]
