# Generated by Django 4.1 on 2022-11-01 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banksampah', '0007_alter_bank_jenis'),
    ]

    operations = [
    ]
