# Generated by Django 4.1 on 2022-10-31 11:53

from django.db import migrations
from django.contrib.auth.models import Group, Permission

class Migration(migrations.Migration):

    dependencies = [
        ('authc', '0001_initial'),
    ]

    operations = [
    ]
