# Generated by Django 4.1 on 2022-10-31 11:53

from django.db import migrations
from django.contrib.auth.models import Group, Permission

def add_group_permissions(apps, schema_editor):
    
    basic_permissions = [
        Permission.objects.get(content_type__app_label='blog', codename='add_comment'),
        Permission.objects.get(content_type__app_label='blog', codename='change_self_comment'),
        Permission.objects.get(content_type__app_label='blog', codename='delete_self_comment'),
    ]

    crew_permissions = [

    ]

    mod_permissions = [
        Permission.objects.get(content_type__app_label='blog', codename='delete_other_comment'),
    ]

    admin_permissions = [
    ]

    group, created = Group.objects.get_or_create(name='user')
    if created:
        for permission in [*basic_permissions]:
            group.permissions.add(permission)
        print('Group "user" created')

    group, created = Group.objects.get_or_create(name='crew')
    if created:
        for permission in [*basic_permissions, *crew_permissions]:
            group.permissions.add(permission)
        print('Group "crew" created')

    group, created = Group.objects.get_or_create(name='moderator')
    if created:
        for permission in [*basic_permissions, *crew_permissions, *mod_permissions]:
            group.permissions.add(permission)
        print('Group "moderator" created')

    group, created = Group.objects.get_or_create(name='administrator')
    if created:
        for permission in [*basic_permissions, *crew_permissions, *mod_permissions, *admin_permissions]:
            group.permissions.add(permission)
        print('Group "administrator" created')


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_post_options'),
        ('authc', '0002_auto_20221031_1853'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
