# Generated by Django 4.1 on 2022-11-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authc', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
