# Generated by Django 4.1 on 2022-11-02 10:45

from django.db import migrations

def add_group_permissions(apps, schema_editor):

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model('auth', 'Permission')
    
    basic_permissions = [
        Permission.objects.get(content_type__app_label='banksampah', codename='view_bank'),
        Permission.objects.get(content_type__app_label='banksampah', codename='add_bank'),
        Permission.objects.get(content_type__app_label='banksampah', codename='change_bank'),
        Permission.objects.get(content_type__app_label='banksampah', codename='delete_bank'),
        Permission.objects.get(content_type__app_label='blog', codename='view_comment'),
        Permission.objects.get(content_type__app_label='blog', codename='view_post'),
        Permission.objects.get(content_type__app_label='crewdashboard', codename='add_location'),
        Permission.objects.get(content_type__app_label='faq', codename='view_faq'),
        Permission.objects.get(content_type__app_label='faq', codename='add_faq'),
        Permission.objects.get(content_type__app_label='faq', codename='change_faq'),
    ]

    crew_permissions = [
        Permission.objects.get(content_type__app_label='crewdashboard', codename='view_location'),
        Permission.objects.get(content_type__app_label='crewdashboard', codename='change_location'),
        Permission.objects.get(content_type__app_label='crewdashboard', codename='delete_location'),
    ]

    mod_permissions = [
        Permission.objects.get(content_type__app_label='faq', codename='delete_faq'),
    ]

    admin_permissions = [
    ]

    group, created = Group.objects.get_or_create(name='user')
    for permission in [*basic_permissions]:
        group.permissions.add(permission)
    print('Group "user" updated')

    group, created = Group.objects.get_or_create(name='crew')
    for permission in [*basic_permissions, *crew_permissions]:
        group.permissions.add(permission)
    print('Group "crew" updated')

    group, created = Group.objects.get_or_create(name='moderator')
    for permission in [*basic_permissions, *crew_permissions, *mod_permissions]:
        group.permissions.add(permission)
    print('Group "moderator" updated')

    group, created = Group.objects.get_or_create(name='administrator')
    for permission in [*basic_permissions, *crew_permissions, *mod_permissions, *admin_permissions]:
        group.permissions.add(permission)
    print('Group "administrator" updated')


class Migration(migrations.Migration):

    dependencies = [
        ('authc', '0005_remove_user_is_admin'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
