# Generated by Django 4.1 on 2022-11-02 10:45

from django.db import migrations

def remove_group_permissions(apps, schema_editor):

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model('auth', 'Permission')
    
    basic_permissions = [
    ]
    
    crew_permissions = [
        Permission.objects.get(content_type__app_label='crewdashboard', codename='delete_location'),
    ]

    mod_permissions = [
    ]

    admin_permissions = [
    ]

    group, created = Group.objects.get_or_create(name='user')
    for permission in [*basic_permissions]:
        group.permissions.remove(permission)
    print('Group "user" updated')

    group, created = Group.objects.get_or_create(name='crew')
    for permission in [*basic_permissions, *crew_permissions]:
        group.permissions.remove(permission)
    print('Group "crew" updated')

    group, created = Group.objects.get_or_create(name='moderator')
    for permission in [*basic_permissions, *crew_permissions, *mod_permissions]:
        group.permissions.remove(permission)
    print('Group "moderator" updated')

    group, created = Group.objects.get_or_create(name='administrator')
    for permission in [*basic_permissions, *crew_permissions, *mod_permissions, *admin_permissions]:
        group.permissions.remove(permission)
    print('Group "administrator" updated')


class Migration(migrations.Migration):

    dependencies = [
        ('authc', '0006_group_perms'),
    ]

    operations = [
        migrations.RunPython(remove_group_permissions)
    ]
