# Generated by Django 4.1 on 2022-12-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alamat',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='kontak',
            new_name='phoneNumber',
        ),
    ]
