# Generated by Django 4.1 on 2022-12-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authc', '0007_group_perms'),
        ('authc', '0008_rename_alamat_user_address_rename_nama_user_name_and_more'),
    ]

    operations = [
    ]
