name: Deployment

on:
  # Deploy saat ada commit yang di-push di branch master.
  push:
    branches:
      - master
  # Deploy secara manual dari GitHub.
  workflow_dispatch:

concurrency:
  group: "heroku"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Check secrets
      run: |
        if [ "${{ secrets.RAILWAY_TOKEN }}" == "" ] || [ "${{ secrets.HEROKU_APP_NAME }}" == "" ] ; then
          exit 1
        fi
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy to Railway
      uses: bervProject/railway-deploy@0.0.7-alpha
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
    - name: Create GitHub deployment
      uses: chrnorm/deployment-action@v2
      with:
        initial-status: success
        token: ${{ github.token }}
        # Assuming you are not using custom domain on Heroku, the target_url
        # will contain the URL to your application hosted under Heroku's
        # subdomain.
        environment-url: https://${{ secrets.HEROKU_APP_NAME }}.up.railway.app
        environment: production
