name: Deployment

on:
  # Deploy saat ada commit yang di-push di branch master.
  push:
    branches:
      - master
  # Deploy secara manual dari GitHub.
  workflow_dispatch:

concurrency:
  group: "heroku"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
    steps:
    - name: Create GitHub deployment
      uses: chrnorm/deployment-action@v2
      with:
        initial-status: success
        token: ${{ github.token }}
        # Assuming you are not using custom domain on Heroku, the target_url
        # will contain the URL to your application hosted under Heroku's
        # subdomain.
        environment-url: https://${{ secrets.HEROKU_APP_NAME }}.up.railway.app
        environment: production
